@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE4MDIxNDIwNjYsImp0aSI6IjhjMmRlNzIzLTUwOTItNDQxOC05ZTcyLTZkNDlkYjZiMGI1ZSIsImlhdCI6MTYwMTUzNzI2NiwiaXNzIjoibG9naW4uYmluZ2dsLm5ldCIsInN1YiI6ImEuYkBjLmRlIiwiVHlwZSI6ImxvZ2luLlVzZXIiLCJEaXNwbGF5TmFtZSI6IlRlc3QgVXNlciIsIkVtYWlsIjoiYS5iQGMuZGUiLCJVc2VySWQiOiIxMjM0NSIsIlVzZXJOYW1lIjoiVXNlcm5hbWUiLCJHaXZlbk5hbWUiOiJUZXN0IiwiU3VybmFtZSI6IlVzZXIiLCJDbGFpbXMiOlsibXlkbXN8aHR0cDovL2xvY2FsaG9zdDozMDAyfEFkbWluIl19.hcFXOaHNC5kX3VmYvpNe2042yqKAOcp2r2zu_YFE3pg


# SEARCH all documents
GET http://localhost:8080/api/v1/documents/search
Authorization: Bearer {{Token}}

###

# GET a specific document
GET http://localhost:8080/api/v1/documents/00433605-716d-4656-a130-a69b7a10e653
Authorization: Bearer {{Token}}

###

# UPDATE a document
POST http://localhost:8080/api/v1/documents
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "id": "00433605-716d-4656-a130-a69b7a10e653",
  "title": "TEST1",
  "alternativeId": "-1pqt26",
  "amount": 0,
  "created": "2014-02-06T23:00:00+07:00",
  "modified": "2014-09-20T18:48:28+07:00",
  "fileName": "/2014_02_07/test.pdf",
  "previewLink": "LzIwMTRfMDJfMDcvdGVzdC5wZGY=",
  "tags": [
    "A"
  ],
  "senders": [
    "B"
  ],
  "invoiceNumber": "123456789"
}
