---
baseconfig:
    ## common application properties
    appName: mydms-go
    hostID: mydms
    environment: Development
    errorPath: /error

    # static assets
    assets:
        assetDir: "../../assets"
        assetPrefix: "/public"

    # configuration for JWT authentication
    security:
        jwtIssuer: issuer
        jwtSecret: secret
        cookieName: login_token
        loginRedirect: "http://localhost:3001"
        claim:
            name: mydms
            url: http://localhost:3002
            roles:
                - User
                - Admin
        cacheDuration: 10m

    # allow cross-origin requests
    cors:
        origins:
            - "http://localhost:8080"
            - "http://localhost:3000"
            - "http://localhost:4200"
            - "http://dev.binggl.net"
            - "https://dev.binggl.net"
            - "http://dev.binggl.net:4200"
        methods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
        headers:
            - "cache-control"
            - "content-type"
            - "pragma"
            - "accept"
            - "authorization"
        credentials: true
        maxAge: 500

    # log settings
    logging:
        filePath: "./logs/mydms-api.log"
        logLevel: debug
        grayLogServer: ""

    # cookies are needed for user-facing sites and messaging
    cookies:
        domain: localhost
        path: "/"
        secure: false
        prefix: mydms

database:
    connectionString: "DATABASE"

filestore:
    region: "us-east-1"
    bucket: "testbucket"
    key: "s3_access_key"
    secret: "s3_access_secret"
    endpoint: "endpoint"

upload:
    allowedFileTypes:
        - "pdf"
        - "jpg"
        - "jpeg"
        - "png"
        - "gif"
    maxUploadSize: 5000000
    uploadPath: "/tmp/"
