---
baseconfig:
    ## common application properties
    appName: mydms-go
    hostID: mydms
    environment: Development
    errorPath: /error

    # static assets
    assets:
        assetDir: "./assets"
        assetPrefix: "/assets"

    # configuration for JWT authentication
    security:
        jwtIssuer: issuer
        jwtSecret: secret
        cookieName: login_token
        loginRedirect: "http://localhost:3001"
        claim:
            name: mydms
            url: http://localhost:3002
            roles:
            - User
            - Admin
        cacheDuration: 10m

    # allow cross-origin requests
    cors:
        origins:
        - "http://localhost:8080"
        - "http://localhost:3000"
        - "http://localhost:4200"
        - "http://dev.binggl.net"
        - "https://dev.binggl.net"
        - "http://dev.binggl.net:4200"
        methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
        headers:
        - "cache-control"
        - "content-type"
        - "pragma"
        - "accept"
        - "authorization"
        credentials: true
        maxAge: 500

    # log settings
    logging:
        filePath: "./logs/mydms-api.log"
        logLevel: debug
        grayLogServer: ""

    # cookies are needed for user-facing sites and messaging
    cookies:
        domain: localhost
        path: "/"
        secure: false
        prefix: mydms

database:
    connectionString: "DATABASE"

upload:
   endpointURL: http://localhost:3000/

filestore:
    region: "region"
    bucket: "bucket"
    key: "key"
    secret: "secret"


