// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "golang.binggl.net/monorepo/pkg/config"

func Error403(env config.Environment) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container\"><div class=\"item\"><img src=\"/public/access-denied.svg\" width=\"100px\"><h2>Access denied</h2><p>You are not loged in or you do not have permission to access this page!</p><a id=\"link-oidc-start\" href=\"https://one.binggl.net/oidc/start\"><button type=\"button\" class=\"btn btn-lg btn-warning\">Login to access the page</button></a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if env == config.Development {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><br><a id=\"link-gettoken\" href=\"/gettoken\"><button type=\"button\" class=\"btn btn-lg btn-danger\">Show me the JWT token for development</button></a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
