root = "."
testdata_dir = "testdata"
tmp_dir = "./tmp"

[build]
  # -------------------------------------------------------------------------
  # core
  # -------------------------------------------------------------------------
  #args_bin = [
  #  "--port",
  #  "3003",
  #  "--basepath",
  #  "./internal/core"
  #]
  #bin = "./tmp/core.api"
  #cmd = "go build -ldflags=\"-X main.Version=NOW -X main.Build=DEV\" -o ./tmp/core.api ./cmd/core/server/main.go"

  # -------------------------------------------------------------------------
  # bookmarks
  # -------------------------------------------------------------------------
  #args_bin = [
  #  "--port",
  #  "3003",
  #  "--basepath",
  #  "./internal/bookmarks"
  #]
  #bin = "./tmp/bookmarks.api"
  #cmd = "go build -ldflags=\"-X main.Version=NOW -X main.Build=DEV\" -o ./tmp/bookmarks.api ./cmd/bookmarks/server/main.go"


  # -------------------------------------------------------------------------
  # mydms
  # -------------------------------------------------------------------------
  args_bin = [
    "--port",
    "3003",
    "--basepath",
    "./internal/mydms"
  ]
  bin = "./tmp/mydms.api"
  cmd = "go build -ldflags=\"-X main.Version=NOW -X main.Build=DEV\" -o ./tmp/mydms.api ./cmd/mydms/server/main.go"

  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend", "caddy", ".vscode", "doc", "tmp", "tools", "upload", "litestream", "_logs"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
