services:

    tokentest:
        build:
            context: ./
            dockerfile: ./tokentest.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: tokentest
        restart:
            always
        environment:
            JWT_COOKIE_NAME: $JWT_COOKIE_NAME
            JWT_ISSUER: $JWTISSUER
            JWT_SECRET: $JWTSECRET
            JWT_USER_EMAIL: $JWT_USER_EMAIL
            JWT_COOKIE_DOMAIN: $JWT_COOKIE_DOMAIN
            REDIRECT_URL: https://dev.binggl.net
            PORT: 3000

    crypter:
        build:
            context: .
            dockerfile: ./crypter.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: crypter
        volumes:
            - ./internal/crypter:/opt/crypter/etc
            - ./_logs:/opt/crypter/logs
        restart:
            always
        environment:
            CR_ENVIRONMENT: Production
            CR_TOKENSECURITY.JWTISSUER: $JWTISSUER
            CR_TOKENSECURITY.JWTSECRET: $JWTSECRET
            CR_LOGGING.FILEPATH: /opt/crypter/logs/crypter-grpc-api.log
            CR_LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER

    core-3001:
        build:
            context: .
            dockerfile: ./core.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: core
        volumes:
            - ./internal/core:/opt/core/etc
            - ./_logs:/opt/core/logs
            - ./upload:/opt/core/uploads
            - ./testdata/sqlite/:/opt/core/db
        restart:
            always
        environment:
            CO_BASECONFIG.ENVIRONMENT: Development
            CO_BASECONFIG.LOGGING.FILEPATH: /opt/core/logs/core-api.log
            CO_BASECONFIG.LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER
            CO_SECURITY.JWTISSUER: $JWTISSUER
            CO_SECURITY.JWTSECRET: $JWTSECRET
            CO_SECURITY.LOGINREDIRECT: https://dev.binggl.net
            CO_OIDC.REDIRECTURL: "https://dev.binggl.net/oidc/signin"
            CO_OIDC.CLIENTID: $OIDC_CLIENTID
            CO_OIDC.CLIENTSECRET: $OIDC_CLIENTSECRET
            CO_UPLOAD.UPLOADPATH: /opt/core/uploads
            CO_UPLOAD.ENCGRPCCONN: crypter:3000
            CO_UPLOAD.MAXUPLOADSIZE: 5000000
            CO_DATABASE.CONNECTIONSTRING: /opt/core/db/integration_core.db

    mydms-3002:
        build:
            context: .
            dockerfile: ./mydms.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: mydms
        volumes:
            - ./internal/mydms:/opt/mydms/etc
            - ./_logs:/opt/mydms/logs
            - ./testdata/sqlite/:/opt/mydms/db
        restart:
            always
        environment:
            MY_BASECONFIG.ENVIRONMENT: Development
            MY_BASECONFIG.SECURITY.JWTISSUER: $JWTISSUER
            MY_BASECONFIG.SECURITY.JWTSECRET: $JWTSECRET
            MY_BASECONFIG.SECURITY.CLAIM.URL: http://localhost:3002
            MY_BASECONFIG.LOGGING.FILEPATH: /opt/mydms/logs/mydms-api.log
            MY_BASECONFIG.LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER
            MY_FILESTORE.REGION: $FILESTORE_REGION
            MY_FILESTORE.BUCKET: $FILESTORE_BUCKET
            MY_FILESTORE.KEY: $FILESTORE_KEY
            MY_FILESTORE.SECRET: $FILESTORE_SECRET
            MY_UPLOAD.ENDPOINTURL: http://core-3001:3000/api/v1
            MY_DATABASE.CONNECTIONSTRING: /opt/mydms/db/integration_mydms.db

    bookmarks-3003:
        build:
            context: .
            dockerfile: ./bookmarks.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: bookmarks
        volumes:
            - ./internal/bookmarks:/opt/bookmarks/etc
            - ./_logs:/opt/bookmarks/logs
            - ./testdata/sqlite/:/opt/bookmarks/db
        restart:
            always
        environment:
            BM_BASECONFIG.ENVIRONMENT: Development
            BM_BASECONFIG.SECURITY.JWTISSUER: $JWTISSUER
            BM_BASECONFIG.SECURITY.JWTSECRET: $JWTSECRET
            BM_BASECONFIG.LOGGING.FILEPATH: /opt/bookmarks/logs/bookmarks-api.log
            BM_BASECONFIG.LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER
            BM_DATABASE.CONNECTIONSTRING: /opt/bookmarks/db/integration_bookmarks.db

    ## the frontend-dev is a simple docker-image which just executes the angular stuff
    ## the local development folder is mounted into the image, giving it access to the necessary files
    frontend-dev:
        build:
            context: .
            dockerfile: ./frontend.dev.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: frontenddev
        volumes:
            - ./frontend:/opt/onefrontend
        restart:
            always

    ## caddy reverse-proxies the development frontend container-imager
    ## therefor just the one-and-only exposed port (apart from the DB) is the https/443 port of caddy
    caddy-frontend-443:
        image: caddy:2-alpine
        ports:
            - "443:443"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./caddy/certs:/opt/caddy/certs
        restart:
            on-failure
