version: '3'

services:

    tokentest:
        build:
            context: .
            dockerfile: ./tokentest.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: tokentest
        restart:
            always
        environment:
            JWT_COOKIE_NAME: $JWT_COOKIE_NAME
            JWT_ISSUER: $JWTISSUER
            JWT_SECRET: $JWTSECRET
            JWT_USER_EMAIL: $JWT_USER_EMAIL
            JWT_COOKIE_DOMAIN: $JWT_COOKIE_DOMAIN
            REDIRECT_URL: https://dev.binggl.net
            PORT: 3000

    crypter:
        build:
            context: .
            dockerfile: ./crypter.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: crypter
        volumes:
            - ./internal/crypter:/opt/crypter/etc
            - ./_logs:/opt/crypter/logs
        restart:
            always
        environment:
            CR_ENVIRONMENT: Production
            CR_TOKENSECURITY.JWTISSUER: $JWTISSUER
            CR_TOKENSECURITY.JWTSECRET: $JWTSECRET
            CR_LOGGING.FILEPATH: /opt/crypter/logs/crypter-grpc-api.log
            CR_LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER

    core-3001:
        build:
            context: .
            dockerfile: ./core.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: core
        volumes:
            - ./internal/core:/opt/core/etc
            - ./_logs:/opt/core/logs
            - ./upload:/opt/core/uploads
            - ./testdata/sqlite/integration:/opt/core/db
            - ./litestream/litestream-integration.yml:/etc/litestream.yml
        restart:
            always
        environment:
            CO_BASECONFIG.ENVIRONMENT: Development
            CO_BASECONFIG.LOGGING.FILEPATH: /opt/core/logs/core-api.log
            CO_BASECONFIG.LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER
            CO_SECURITY.JWTISSUER: $JWTISSUER
            CO_SECURITY.JWTSECRET: $JWTSECRET
            CO_SECURITY.LOGINREDIRECT: https://dev.binggl.net
            CO_OIDC.REDIRECTURL: "https://dev.binggl.net/oidc/signin"
            CO_OIDC.CLIENTID: $OIDC_CLIENTID
            CO_OIDC.CLIENTSECRET: $OIDC_CLIENTSECRET
            CO_UPLOAD.UPLOADPATH: /opt/core/uploads
            CO_UPLOAD.ENCGRPCCONN: crypter:3000
            CO_UPLOAD.MAXUPLOADSIZE: 5000000
            CO_DATABASE.CONNECTIONSTRING: /opt/core/db/core.db
            CONNECTIONSTRING: /opt/core/db/core.db
            REPLICA_URL: $CORE_REPLICA_URL
            LITESTREAM_ACCESS_KEY_ID: $LITESTREAM_ACCESS_KEY_ID
            LITESTREAM_SECRET_ACCESS_KEY: $LITESTREAM_SECRET_ACCESS_KEY
            BASEPATH: /opt/core
            BINARYNAME: core.api
            PORT: 3000
            HOSTNAME: 0.0.0.0

    mydms-3002:
        build:
            context: .
            dockerfile: ./mydms.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: mydms
        volumes:
            - ./internal/mydms:/opt/mydms/etc
            - ./_logs:/opt/mydms/logs
            - ./testdata/sqlite/integration:/opt/mydms/db
            - ./litestream/litestream-integration.yml:/etc/litestream.yml
        restart:
            always
        environment:
            MY_BASECONFIG.ENVIRONMENT: Development
            MY_BASECONFIG.SECURITY.JWTISSUER: $JWTISSUER
            MY_BASECONFIG.SECURITY.JWTSECRET: $JWTSECRET
            MY_BASECONFIG.SECURITY.CLAIM.URL: http://localhost:3002
            MY_BASECONFIG.LOGGING.FILEPATH: /opt/mydms/logs/mydms-api.log
            MY_BASECONFIG.LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER
            MY_FILESTORE.REGION: $FILESTORE_REGION
            MY_FILESTORE.BUCKET: $FILESTORE_BUCKET
            MY_FILESTORE.KEY: $FILESTORE_KEY
            MY_FILESTORE.SECRET: $FILESTORE_SECRET
            MY_UPLOAD.ENDPOINTURL: http://core-3001:3000/api/v1
            MY_DATABASE.CONNECTIONSTRING: /opt/mydms/db/mydms.db
            CONNECTIONSTRING: /opt/mydms/db/mydms.db
            REPLICA_URL: $MYDMS_REPLICA_URL
            LITESTREAM_ACCESS_KEY_ID: $LITESTREAM_ACCESS_KEY_ID
            LITESTREAM_SECRET_ACCESS_KEY: $LITESTREAM_SECRET_ACCESS_KEY
            BASEPATH: /opt/mydms
            BINARYNAME: mydms.api
            PORT: 3000
            HOSTNAME: 0.0.0.0

    bookmarks-3003:
        build:
            context: .
            dockerfile: ./bookmarks.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
        image: bookmarks
        volumes:
            - ./internal/bookmarks:/opt/bookmarks/etc
            - ./_logs:/opt/bookmarks/logs
            - ./testdata/sqlite/dev:/opt/mydms/db
            - ./litestream/litestream-integration.yml:/etc/litestream.yml
        restart:
            always
        environment:
            BM_BASECONFIG.ENVIRONMENT: Development
            BM_BASECONFIG.SECURITY.JWTISSUER: $JWTISSUER
            BM_BASECONFIG.SECURITY.JWTSECRET: $JWTSECRET
            BM_BASECONFIG.LOGGING.FILEPATH: /opt/bookmarks/logs/bookmarks-api.log
            BM_BASECONFIG.LOGGING.GRAYLOGSERVER: $LOGGING_GRAYLOGSERVER
            BM_DATABASE.CONNECTIONSTRING: /opt/bookmarks/db/bookmarks.db
            CONNECTIONSTRING: /opt/bookmarks/db/bookmarks.db
            REPLICA_URL: $BOOKMARKS_REPLICA_URL
            LITESTREAM_ACCESS_KEY_ID: $LITESTREAM_ACCESS_KEY_ID
            LITESTREAM_SECRET_ACCESS_KEY: $LITESTREAM_SECRET_ACCESS_KEY
            BASEPATH: /opt/bookmarks
            BINARYNAME: bookmarks.api
            PORT: 3000
            HOSTNAME: 0.0.0.0

    caddy-integration-frontend-443:
        build:
            context: .
            dockerfile: ./caddy.Dockerfile
            args:
                buildtime_variable_arch: $ARCH
                FRONTEND_MODE: integration
        image: frontend
        ports:
            - "443:443"
        volumes:
            - ./caddy/Caddyfile.integration:/etc/caddy/Caddyfile
            - ./caddy/certs:/opt/caddy/certs
        restart:
            on-failure
