version: '3'

services:
    
    login-3001:
        build: 
            context: .
            dockerfile: ./login.Dockerfile
        image: login
        networks:
            - app-network
        ports:
            - "3001:3000"
        volumes:
            - ./login-go:/opt/login/etc
        restart:
            on-failure

    mydms-3002:
        build: 
            context: .
            dockerfile: ./mydms.Dockerfile
        image: mydms
        networks:
            - app-network
        ports:
            - "3002:3000"
        volumes:
            - ./mydms-go:/opt/mydms/etc
        restart:
            on-failure

    bookmarks-3003:
        build: 
            context: .
            dockerfile: ./bookmarks.Dockerfile
        image: bookmarks
        networks:
            - app-network
        ports:
            - "3003:3000"
        volumes:
            - ./bookmarks/_etc:/opt/bookmarks/etc
        restart:
            on-failure

    onefrontend-3000:
        build: 
            context: .
            dockerfile: ./onefrontend.Dockerfile
        image: onefrontend
        networks:
            - app-network
        ports:
            - "3000:3000"
        volumes:
            - ./onefrontend/etc:/opt/onefrontend/etc
        restart:
            on-failure

networks:
    app-network: {}