---
    tokenSecurity:
        jwtIssuer: issuer
        jwtSecret: secret
        claim:
            name: bookmarks
            url: http://localhost:3003
            roles:
            - User
        cacheDuration: 10m

    logging:
        filePath: "./logs/filecrypter-api.log"
        logLevel: debug


    # common application settings
    serviceName: filecrypter
    hostID: localhost
    environment: Development
