# Go
# Build and test your Go application.
# Add steps that save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_BUILDKIT: 1
  TSTAMP: $[format('{0:yyyyMMdd}', pipeline.startTime)]

steps:
- bash: |
    echo "##vso[task.setvariable variable=githash]${BUILDTIME_VARIABLE_COMMIT:0:7}"
  displayName: 'Calc Githash'

- bash: |
    echo "using Git Hash $GITHASH"
  displayName: 'Show Githash'

- task: Docker@2
  displayName: 'Login to github packages (docker.pkg.github.com)'
  inputs:
    command: login
    containerRegistry: github_docker_images


## --------------------------------------------------------------------------
## docker build
## --------------------------------------------------------------------------

- task: Docker@2
  displayName: 'Build bookmarks'
  inputs:
    command: build
    Dockerfile: 'bookmarks.Dockerfile'
    repository: bihe/monorepo/bookmarks-go
    tags: |
      latest
      $(githash)
    arguments: |
      --build-arg buildtime_variable_version=1.0.$(Build.BuildId)
      --build-arg buildtime_variable_timestamp=$(TSTAMP)
      --build-arg buildtime_variable_commit=$(githash)

- task: Docker@2
  displayName: 'Build mydms'
  inputs:
    command: build
    Dockerfile: 'mydms.Dockerfile'
    repository: bihe/monorepo/mydms-go
    tags: |
      latest
      $(githash)
    arguments: |
      --build-arg buildtime_variable_version=2.0.$(Build.BuildId)
      --build-arg buildtime_variable_timestamp=$(TSTAMP)
      --build-arg buildtime_variable_commit=$(githash)

- task: Docker@2
  displayName: 'Build login'
  inputs:
    command: build
    Dockerfile: 'login.Dockerfile'
    repository: bihe/monorepo/login-go
    tags: |
      latest
      $(githash)
    arguments: |
      --build-arg buildtime_variable_version=2.0.$(Build.BuildId)
      --build-arg buildtime_variable_timestamp=$(TSTAMP)
      --build-arg buildtime_variable_commit=$(githash)

- task: Docker@2
  displayName: 'Build onefrontend-go'
  inputs:
    command: build
    Dockerfile: 'onefrontend.Dockerfile'
    repository: bihe/monorepo/onefrontend-go
    tags: |
      latest
      $(githash)
    arguments: |
      --build-arg buildtime_variable_version=2.0.$(Build.BuildId)
      --build-arg buildtime_variable_timestamp=$(TSTAMP)
      --build-arg buildtime_variable_commit=$(githash)
      --build-arg FRONTEND_MODE=$(FRONTEND_MODE)


## --------------------------------------------------------------------------
## docker publish
## --------------------------------------------------------------------------

- task: Docker@2
  displayName: 'Push bookmarks'
  inputs:
    containerRegistry: github_docker_images
    command: push
    repository: bihe/monorepo/bookmarks-go
    tags: |
      latest
      $(githash)

- task: Docker@2
  displayName: 'Push mydms'
  inputs:
    containerRegistry: github_docker_images
    command: push
    repository: bihe/monorepo/mydms-go
    tags: |
      latest
      $(githash)

- task: Docker@2
  displayName: 'Push login'
  inputs:
    containerRegistry: github_docker_images
    command: push
    repository: bihe/monorepo/login-go
    tags: |
      latest
      $(githash)

- task: Docker@2
  displayName: 'Push onefrontend'
  inputs:
    containerRegistry: github_docker_images
    command: push
    repository: bihe/monorepo/onefrontend-go
    tags: |
      latest
      $(githash)
