---
tokenSecurity:
    jwtIssuer: issuer
    jwtSecret: secret
    claim:
        name: crypter
        url: http://localhost:3004
        roles:
        - User
    cacheDuration: 10m

logging:
    filePath: "../../../_logs/crypter-grpc-api.log"
    logLevel: debug
    grayLogServer: ""

# common application settings
serviceName: crypter
hostID: localhost
environment: Development
