---
# configuration for JWT authentication
security:
    jwtIssuer: issuer
    jwtSecret: secret
    cookieName: login_token
    loginRedirect: "http://localhost:3001/auth/flow?~site=bookmarks&~url=http%3A%2F%2Flocalhost%3A3003%3Fvalid%3Dtrue"
    claim:
        name: bookmarks
        url: http://localhost:3003
        roles:
        - User
    cacheDuration: 10m

database:
    connectionString: "root:mariadb@tcp(localhost:3306)/bookmarks?parseTime=true&sql_mode='PIPES_AS_CONCAT'"
    dialect: mysql

logging:
    filePath: "./logs/bookmarks-api.log"
    requestPath: "./logs/requests.log"
    logLevel: debug

# cookies are needed for user-facing sites and messaging
cookies:
    domain: localhost
    path: "/"
    secure: false
    prefix: bookmarks

cors:
    origins:
    - "http://localhost:3000"
    - "http://localhost:4200"
    methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    headers:
    - "cache-control"
    - "content-type"
    - "pragma"
    - "accept"
    - "authorization"
    credentials: true
    maxAge: 500

# common application settings
appName: bookmarks-go
hostID: bookmarks

errorPath: /error
environment: Development
# place to store the downloaded favicons
faviconUploadPath: "./uploads/"
defaultFavicon: "./assets/favicon.ico"
