---
baseconfig:
    ## common application properties
    appName: bookmarks-go
    hostID: localhost-bookmarks
    environment: Development
    errorPath: /error

    # allow cross-origin requests
    cors:
        origins:
        - "http://localhost:8080"
        - "http://localhost:3000"
        - "http://localhost:4200"
        - "http://dev.binggl.net"
        - "https://dev.binggl.net"
        - "http://dev.binggl.net:4200"
        methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "OPTIONS"
        headers:
        - "cache-control"
        - "content-type"
        - "pragma"
        - "accept"
        - "authorization"
        credentials: true
        maxAge: 500

    # log settings
    logging:
        filePath: "./logs/bookmarks-api.log"
        logLevel: debug
        grayLogServer: ""

    # cookies are needed for user-facing sites and messaging
    cookies:
        domain: dev.binggl.net
        path: "/"
        secure: false
        prefix: bookmarks

    security:
        jwtIssuer: issuer
        jwtSecret: secret
        cookieName: login_token
        loginRedirect: "http://localhost:3001/auth/flow?~site=bookmarks&~url=http%3A%2F%2Flocalhost%3A3003%3Fvalid%3Dtrue"
        claim:
            name: bookmarks
            url: http://localhost:3003
            roles:
            - User
        cacheDuration: 10m

    # static assets
    assets:
        assetDir: "./assets"
        assetPrefix: "/public"

database:
    connectionString: "DATABASE"

# place to store the downloaded favicons
faviconUploadPath: "./uploads/"
