name: Create and publish a Docker images

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  GIT_COMMIT_SHA: ${{ github.sha }}
  BUILD_ID: ${{ github.run_id }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ghcr login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Provide the abbrev git-commit-hash
        id: githash
        run: |
          export GIT_HASH="${GIT_COMMIT_SHA:0:7}"
          echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: |
          echo "TSTAMP=date::$(date +'yyyyMMdd')" >> $GITHUB_ENV

      - name: "Build :: bookmarks"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bookmarks.Dockerfile
          build-args: |
            --build-arg buildtime_variable_version=1.0.${{ env.BUILD_ID }}
            --build-arg buildtime_variable_timestamp=${{ env.TSTAMP }}
            --build-arg buildtime_variable_commit=${{ env.GIT_HASH }}
          push: false
          tags: |
            latest
            ${{ env.GIT_HASH }}
