name: "Container: Build and publish"

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  GIT_COMMIT_SHA: ${{ github.sha }}
  BUILD_ID: ${{ github.run_id }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ghcr login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Provide the abbrev git-commit-hash
        id: githash
        run: |
          export GIT_HASH="${GIT_COMMIT_SHA:0:7}"
          echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      # ---------------------------------------------------------------------

      - name: "Metadata :: bookmarks"
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/bihe/monorepo/bookmarks
          tags: |
            latest
            ${{ env.GIT_HASH }}

      - name: "Build :: bookmarks"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bookmarks.Dockerfile
          build-args: |
            buildtime_variable_version=${{ env.BUILD_ID }}
            buildtime_variable_timestamp=${{steps.date.outputs.date}}
            buildtime_variable_commit=${{ env.GIT_HASH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # ---------------------------------------------------------------------

      - name: "Metadata :: core"
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/bihe/monorepo/core
          tags: |
            latest
            ${{ env.GIT_HASH }}

      - name: "Build :: core"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core.Dockerfile
          build-args: |
            buildtime_variable_version=${{ env.BUILD_ID }}
            buildtime_variable_timestamp=${{steps.date.outputs.date}}
            buildtime_variable_commit=${{ env.GIT_HASH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
