name: Build and Test

# This workflow will run on main branch and on any pull requests targeting main
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: '$GITHUB_WORKSPACE/go.mod'
      - run: go version

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: |
          go version
          go get -v -t -d ./...
          go build ./...

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: '$GITHUB_WORKSPACE/go.mod'
      - run: go version

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Unit tests.
        run: |
          make coverage

      - name: Upload Coverage report to CodeCov
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode atomic 2>&1 ./...; ec=$?
          echo "go test result is - $ec"
          if [ $ec == 0 ]; then
            echo "do codecov upload"
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}
          fi
