name: Build and Test

# This workflow will run on main branch and on any pull requests targeting main
on:
  push:
    branches:
      - main
  pull_request:

jobs:

  setup:
    name: Setup environment
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17


  build:
    name: Build
    needs: [setup]
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          go version
          go get -v -t -d ./...
          go build ./...

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: |
          make coverage

      - name: Upload Coverage report to CodeCov
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode atomic 2>&1 ./...; ec=$?
          echo "go test result is - $ec"
          if [ $ec == 0 ]; then
            echo "do codecov upload"
            bash <(curl -s https://codecov.io/bash) -F monorepo
          fi
