name: "Deploy: Frontend @ local"

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  REPOSITORY: bihe/monorepo

jobs:
  deploy-latest-frontend:
    runs-on: self-hosted

    steps:
      - name: Deploy Frontend Container
        run: |
              sudo /var/www/docker/frontend/renew.sh
        working-directory: /var/www/docker/frontend
